tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import tugas_auth.urls as auth
import tugas_status.urls as status
import tugas_main.urls as main
import tugas_profile.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include(auth, namespace='auth')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^', include(main, namespace='main')),
]

tugas_auth/urls.py
from django.conf.urls import url
from .views import login, logout

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
]

tugas_main/urls.py
from django.conf.urls import url
from .views import landing_page, dashboard, my_profile, my_history, my_status, my_friends, profile, status, history, other_dashboard, edit_profile, expertise_settings

urlpatterns = [
    url(r'^$', landing_page, name='landing_page'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^dashboard/profile/$', my_profile, name='my_profile'),
    url(r'^dashboard/profile/edit$', edit_profile, name='edit_profile'),
    url(r'^dashboard/profile/expertise$', expertise_settings, name='expertise_settings'),
    url(r'^dashboard/history/$', my_history, name='my_history'),
    url(r'^dashboard/status/$', my_status, name='my_status'),
    url(r'^dashboard/friends/$', my_friends, name='my_friends'),
    url(r'^view/(?P<npm>.*)/$', other_dashboard, name='other_dashboard'),
    url(r'^view/(?P<npm>.*)/profile$', profile, name='profile'),
    url(r'^view/(?P<npm>.*)/status$', status, name='status'),
    url(r'^view/(?P<npm>.*)/history$', history, name='history'),
]

tugas_profile/urls.py
from django.conf.urls import url
from .views import update_profile, add_expertise, delete_expertise

urlpatterns = [
    url(r'^update/$', update_profile, name='update_profile'),
    url(r'^add_expertise/$', add_expertise, name='add_expertise'),
    url(r'^delete_expertise/(?P<id>.*)/$', delete_expertise, name='delete_expertise')
]

tugas_status/urls.py
from django.conf.urls import url
from .views import add_status

urlpatterns = [
    url(r'^add/$', add_status, name='add_status'),
]

tugas_main/models.py
from django.db import models

# Create your models here.

tugas_main/views.py
from django.shortcuts import render
from tugas_auth.auth_tools import *
from django.http import HttpResponseNotFound
from django.urls import reverse
from tugas_status.models import Status
from tugas_profile.profile_utils import *
from django.contrib.staticfiles.templatetags.staticfiles import static
import requests

# Create your views here.
def landing_page(request):
    if is_logged_in(request):
        return HttpResponseRedirect(reverse('main:dashboard'))
    else:
        return render(request, 'main/landing_page.html', {'profiles': Profile.objects.all()})

@authenticated
def dashboard(request):
    return my_profile(request)

@authenticated
def my_profile(request):
    return profile(request, get_npm(request))

@authenticated
def my_history(request):
    return history(request, get_npm(request))

@authenticated
def my_status(request):
    return status(request, get_npm(request))

@authenticated
def my_friends(request):
    response = dict()
    prepare_response_for_base(request, get_user(request), response)
    response['friend_dict'] = []
    for profile in Profile.objects.all():
        one_expertise = get_one_expertise(profile.user)
        if one_expertise is None:
            one_expertise = "No expertise"
        else:
            one_expertise = one_expertise.skill
        response['friend_dict'].append({
            'friend_name': profile.first_name + " " + profile.last_name,
            'npm': profile.user.npm,
            'angkatan': profile.batch,
            'keahlian': one_expertise
        })
    return render(request, 'main/friends.html', response)

@authenticated
def edit_profile(request):
    response = dict()
    prepare_response_for_base(request, get_user(request), response)
    return render(request, 'main/profile_edit.html', response)

@authenticated
def expertise_settings(request):
    response = dict()
    user = get_user(request)
    response['expertises'] = get_expertises_from_user(user)
    prepare_response_for_base(request, user, response)
    return render(request, 'main/expertise_settings.html', response)

def other_dashboard(request, npm):
    return profile(request, npm)

def profile(request, npm):
    view_user = get_user_from_npm(npm)
    if view_user is None:
        return HttpResponseNotFound()

    response = dict()

    profile = get_profile_from_user(view_user)
    if profile is not None:
        response['first_name'] = profile.first_name
        response['last_name'] = profile.last_name
        response['npm'] = view_user.npm
        response['batch'] = profile.batch
        response['email'] = profile.email
        response['linkedin_url'] = profile.linkedin_url
    else:
        response['first_name'] = "Unknown"
        response['last_name'] = "Unknown"
        response['npm'] = view_user.npm
        response['batch'] = "Unknown"
        response['email'] = "Unknown"
        response['linkedin_url'] = "Unknown"

    response['expertises'] = get_expertises_from_user(view_user)

    prepare_response_for_base(request, view_user, response)
    return render(request, 'main/profile.html', response)


def status(request, npm):
    view_user = get_user_from_npm(npm)
    if view_user is None:
        return HttpResponseNotFound()

    response = dict()
    response['status_list'] = Status.objects.filter(user=view_user).order_by('-created_at')
    prepare_response_for_base(request, view_user, response)
    return render(request, 'main/status.html', response)

def history(request, npm):
    view_user = get_user_from_npm(npm)
    if view_user is None:
        return HttpResponseNotFound()

    response = dict()
    response['histories'] = requests.get('https://private-e52a5-ppw2017.apiary-mock.com/riwayat').json()
    prepare_response_for_base(request, view_user, response)

    return render(request, 'main/history.html', response)


def prepare_response_for_base(request, user_to_view, response):
    own_profile = is_logged_in(request) and (get_npm(request) == user_to_view.npm)
    profile = get_profile_from_user(user_to_view)
    npm = user_to_view.npm
    name = "Unknown"
    profile_picture_url = static('img/PP.jpg')
    if profile is not None:
        name = profile.first_name + " " + profile.last_name
        profile_picture_url = profile.profile_picture_url
    status_count = Status.objects.filter(user=user_to_view).count()
    latest_status = ""
    if status_count > 0:
        latest_status = Status.objects.filter(user=user_to_view).order_by('-created_at')[0].content

    add_dict = {
        'logged_in': is_logged_in(request),
        'own_profile': own_profile,
        'npm': npm,
        'name': name,
        'status_count': status_count,
        'latest_status': latest_status,
        'profile_picture_url': profile_picture_url,
        'needs_to_edit': (own_profile and (profile is None))
    }

    response.update(add_dict)

tugas_main/templates/main/expertise_settings.html
{% extends 'main/layout/base.html' %}
{% block content %}
    <div class="container">
        <h3>
            Add expertise:
        </h3>
        <form action="{% url 'profile:add_expertise' %}" method="POST">
            {% csrf_token %}
            <div class="row form-group">
                <input type="text" class="input-sm col-xs-12 pull-left" placeholder="Skill" name="skill">
                <select class="col-xs-12 form-control pull-right" name="level">
                    <option>Low</option>
                    <option>Medium</option>
                    <option>High</option>
                </select>
            </div>
            <div class="row">
                <input type="submit" class="btn btn-confirm">
            </div>
        </form>
    </div>
    <div class="table-responsive">
        <table class="table table-striped" align="center">
            <thead>
                <th> No </th>
                <th> Skill </th>
                <th> Expertise </th>
                <th></th>
            </thead>
            <tbody>
                {% for expertise in expertises %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ expertise.skill }}</td>
                    {% if expertise.level == "Low" %}
                        <td style="color:darkred">Low</td>
                    {% elif expertise.level == "Medium" %}
                        <td style="color:darkgreen">Medium</td>
                    {% else %}
                        <td style="color:black">High</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'profile:delete_expertise' expertise.id %}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block script %}
<script>
    document.getElementById("profile").className = "active";
</script>
{% endblock %}

tugas_main/templates/main/friends.html
{% extends 'main/layout/base.html' %}

{% block content %}
<div class = "container">

    <div class="row">
            <form id = "myRadio">
                    <label class="radio-inline">
                      <input type="radio" name="optradio" id="filter_0" onclick="setFilter(this.value)" value="0">Name
                    </label>
                    <label class="radio-inline">
                      <input type="radio" name="optradio" id="filter_1" onclick="setFilter(this.value)" value="1">NPM
                    </label>
                    <label class="radio-inline">
                      <input type="radio" name="optradio" id="filter_2" onclick="setFilter(this.value)" value="2">Batch
                    </label>
                    <label class="radio-inline">
                            <input type="radio" name="optradio"  id="filter_3" onclick="setFilter(this.value)" value="3">Expertise
                          </label>
                  </form>

                </div>
                <div class = "row">
                    <input style = "margin-top: 10px;" type="text" placeholder="Search Something" class = "form-control" id = "text" onKeyUp="filter()" size="100%">
                </div>
            </form>
    </div>

    <div class = "row>">
        <table class="table table-hover display"  id="example" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>NPM</th>
                    <th>Batch</th>
                    <th>Expertise</th>
                </tr>
            </thead>
            <tbody>
                {% for friend_data in friend_dict %}
                    <tr>
                        <td class="name">{{ friend_data.friend_name }}</td>
                        <td class="npm">{{ friend_data.npm }}</td>
                        <td class="batch">{{ friend_data.angkatan }}</td>
                        <td class="expertise">{{ friend_data.keahlian }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</div>

</div>
{% endblock %}
{% block script %}

<script>
document.getElementById('friends').className = 'active';

var selectedValue = 0;

function setFilter(value) {
    selectedValue = value;
}

function filter() {
    tr = document.getElementsByTagName('tr');
    needle = document.getElementById("text").value.toUpperCase();
    for (var i=1;i<tr.length; i++) {
        td = tr[i].getElementsByTagName('td')[selectedValue];
        if (td) {
            if (td.innerHTML.toUpperCase().indexOf(needle) > -1) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }

}

</script>

{% endblock %}

tugas_main/templates/main/history.html
{% extends 'main/layout/base.html' %}
{% block content %}
    <div class="table-responsive">
        <table class="table table-striped" align="center">
            <thead>
                <th> No </th>
                <th> Nama Mata Kuliah </th>
                <th> Kode Kelas </th>
                <th> Nilai </th>
                <th> Term </th>
            </thead>
            <tbody>
                {% for history in histories %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ history.kelas.nm_mk_cl.nm_mk }}</td>
                    <td> {{ history.kelas.kd_kls }}</td>
                    <td> {{ history.nilai }}</td>
                    <td> {{ history.term }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block script %}
<script>
    document.getElementById("history").className = "active"
</script>
{% endblock %}

tugas_main/templates/main/landing_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>
        {% block title %} Tugas 2 PPW {% endblock %}
    </title>


</head>
<body>

<content>
    <div class="table-responsive">
        <table class="table table-striped" align="center">
            <thead>
                <th> No </th>
                <th> Participant </th>
                <th> Profile </th>
            </thead>
            <tbody>
                {% for profile in profiles %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ profile.first_name }} {{ profile.last_name }}</td>
                    <td> <a href="{% url 'main:profile' profile.user.npm %}" class="btn btn-primary">View profile</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container">

        <a href="{% url 'auth:login' %}" class="col-xs-12 btn btn-primary">Login</a>
    </div>
</content>

<!-- Jquery n Bootstrap Script -->
</body>
</html>

tugas_main/templates/main/profile.html
{% extends 'main/layout/base.html' %}

{% block content %}
    <h3>First Name</h3>
    <p>{{ first_name }}</p>
    <br/>

    <h3>Last Name</h3>
    <p>{{ last_name }}</p>
    <br/>

    <h3>NPM</h3>
    <p>{{ npm }}</p>
    <br/>

    <h3>Batch</h3>
    <p>{{ batch }}</p>
    <br/>

    <h3>Email</h3>
    <p>{{ email }}</p>
    <br/>

    <h3>LinkedIn Profile</h3>
    <p>{{ linkedin_url }}</p>
    <br/>

    <h3>Expertise</h3>
    {% if own_profile %}
        <a href="{% url 'main:expertise_settings' %}" class="btn btn-primary">Expertises setting</a>
    {% endif %}
    <div class="table-responsive">
        <table class="table table-striped" align="center">
            <thead>
                <th> No </th>
                <th> Skill </th>
                <th> Expertise </th>
            </thead>
            <tbody>
                {% for expertise in expertises %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ expertise.skill }}</td>
                    {% if expertise.level == "Low" %}
                        <td style="color:darkred">Low</td>
                    {% elif expertise.level == "Medium" %}
                        <td style="color:darkgreen">Medium</td>
                    {% else %}
                        <td style="color:black">High</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br/>


{% endblock %}

{% block script %}
<script>
    document.getElementById("profile").className = "active"
</script>
{% endblock %}

tugas_main/templates/main/profile_edit.html
{% extends 'main/layout/base.html' %}
{% load staticfiles %}
{% block head_script %}
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81axywudtmoawd
    onLoad:    onLoad
    authorize: true
    lang:      en_US
</script>
{% endblock %}

{% block content %}
    <form action="{% url 'profile:update_profile' %}" method="POST">
        {% csrf_token %}
        <div class="container" id="form">
            <div class="row">
                <div id="linkedin-button" class="col-xs-5 pull-left">
                    <h3>
                        Login to LinkedIn to continue editing
                    </h3>
                    <script type="in/Login"></script>
                </div>
                <img id="pp-image" src="{% static 'img/PP.jpg' %}" class="col-xs-5 pull-right" style="max-width:250px">
                <input type="text" id="profile-picture-url" name="profile_picture_url" value="{% static 'img/PP.jpg' %}" hidden>
            </div>

            <div class="row">
                <h3 class="col-xs-5">LinkedIn URL</h3>
            </div>

            <div class="row">
                <input type="text" id="linkedin-url" name="linkedin_url" class="col-xs-5 input-sm" value="" readonly/>
            </div>

            <div class="row">
                <h3 class="col-xs-5">First Name</h3>
                <h3 class="col-xs-5 pull-right">Last Name</h3>
            </div>
            <div class="row">
                <input type="text" id="first-name" name="first_name" class="col-xs-5 input-sm" value="" readonly/>
                <input type="text" id="last-name" name="last_name" class="col-xs-5 pull-right input-sm" value="" readonly/>
            </div>

            <div class="row">
                <h3 class="col-xs-5">Email Address</h3>
                <h3 class="col-xs-5 pull-right">Batch</h3>
            </div>
            <div class="row form-group">
                <input type="text" id="email" name="email" class="col-xs-5 input-sm" value="" readonly />
                <input type="number" name="batch" class="col-xs-5 pull-right input-sm" value="2016" />
            </div>

            <div class="row">
                <input type="submit" id="submit-button" class="btn btn-confirm" style="display: none">
            </div>
        </div>
    </form>
{% endblock %}

{% block script %}
<script>

document.getElementById("profile").className = "active";


function onLoad() {
    IN.Event.on(IN, 'auth', getData);
}

function getData() {
    IN.API.Profile("me")
    .fields("firstName",
        "lastName",
        "industry",
        "location:(name)",
        "picture-url",
        "headline",
        "summary",
        "num-connections",
        "public-profile-url",
        "distance",
        "positions",
        "email-address",
        "educations",
        "date-of-birth")
    .result(printData)
    .error(printError);
}

function printData(data) {
    data = data.values[0]
    document.getElementById('linkedin-button').style="display:none";
    document.getElementById('linkedin-url').value=data.publicProfileUrl;
    if (data.hasOwnProperty('pictureUrl')) {
        document.getElementById('pp-image').src=data.pictureUrl;
        document.getElementById('profile-picture-url').value=data.pictureUrl;
    }
    document.getElementById('first-name').value=data.firstName;
    document.getElementById('last-name').value=data.lastName;
    document.getElementById('email').value=data.emailAddress;
    document.getElementById('submit-button').removeAttribute('style');

}

function printError(data) {
    console.log(data);
}



</script>
{% endblock %}

tugas_main/templates/main/status.html
{% extends 'main/layout/base.html' %}
{% block content %}
    <div class="container">
        {% for status in status_list %}
            <div class="row">
                {{ status.created_at }}
                <div class="well">
                    {{ status.content }}
                </div>
            </div>
        {% endfor %}
    </div>
    {% if own_profile %}
        <div class="container">
            <form action="{% url 'status:add_status' %}" method="POST">
                {% csrf_token %}

                <div class="row form-group">
                    <input type="text" id="status" name="status" class="col-xs-12 input-lg" required>
                </div>
                <div class="row form-group">
                    <input type="submit" class="btn btn-primary pull-right">
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

{% block script %}
<script>
    document.getElementById("status").className = "active"
</script>
{% endblock %}