tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import tugas_auth.urls as auth
import tugas_status.urls as status
import tugas_main.urls as main
import tugas_profile.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include(auth, namespace='auth')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^', include(main, namespace='main')),
]

tugas_auth/urls.py
from django.conf.urls import url
from .views import login, logout

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
]

tugas_main/urls.py
from django.conf.urls import url
from .views import landing_page, dashboard, my_profile, my_history, my_status, my_friends, profile, status, history, other_dashboard, edit_profile, expertise_settings

urlpatterns = [
    url(r'^$', landing_page, name='landing_page'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^dashboard/profile/$', my_profile, name='my_profile'),
    url(r'^dashboard/profile/edit$', edit_profile, name='edit_profile'),
    url(r'^dashboard/profile/expertise$', expertise_settings, name='expertise_settings'),
    url(r'^dashboard/history/$', my_history, name='my_history'),
    url(r'^dashboard/status/$', my_status, name='my_status'),
    url(r'^dashboard/friends/$', my_friends, name='my_friends'),
    url(r'^view/(?P<npm>.*)/$', other_dashboard, name='other_dashboard'),
    url(r'^view/(?P<npm>.*)/profile$', profile, name='profile'),
    url(r'^view/(?P<npm>.*)/status$', status, name='status'),
    url(r'^view/(?P<npm>.*)/history$', history, name='history'),
]

tugas_main/models.py
from django.db import models

# Create your models here.

tugas_main/views.py
from django.shortcuts import render
from tugas_auth.auth_tools import *
from django.http import HttpResponseNotFound
from django.urls import reverse
from tugas_status.models import Status
from tugas_profile.profile_utils import *
from django.contrib.staticfiles.templatetags.staticfiles import static
import requests

# Create your views here.
def landing_page(request):
    if is_logged_in(request):
        return HttpResponseRedirect(reverse('main:dashboard'))
    else:
        return render(request, 'main/landing_page.html', {'profiles': Profile.objects.all()})

@authenticated
def dashboard(request):
    return my_profile(request)

@authenticated
def my_profile(request):
    return profile(request, get_npm(request))

@authenticated
def my_history(request):
    return history(request, get_npm(request))

@authenticated
def my_status(request):
    return status(request, get_npm(request))

@authenticated
def my_friends(request):
    response = dict()
    prepare_response_for_base(request, get_user(request), response)
    response['friend_dict'] = []
    for profile in Profile.objects.all():
        one_expertise = get_one_expertise(profile.user)
        if one_expertise is None:
            one_expertise = "No expertise"
        else:
            one_expertise = one_expertise.skill
        response['friend_dict'].append({
            'friend_name': profile.first_name + " " + profile.last_name,
            'npm': profile.user.npm,
            'angkatan': profile.batch,
            'keahlian': one_expertise
        })
    return render(request, 'main/friends.html', response)

@authenticated
def edit_profile(request):
    response = dict()
    prepare_response_for_base(request, get_user(request), response)
    return render(request, 'main/profile_edit.html', response)

@authenticated
def expertise_settings(request):
    response = dict()
    user = get_user(request)
    response['expertises'] = get_expertises_from_user(user)
    prepare_response_for_base(request, user, response)
    return render(request, 'main/expertise_settings.html', response)

def other_dashboard(request, npm):
    return profile(request, npm)

def profile(request, npm):
    view_user = get_user_from_npm(npm)
    if view_user is None:
        return HttpResponseNotFound()

    response = dict()

    profile = get_profile_from_user(view_user)
    if profile is not None:
        response['first_name'] = profile.first_name
        response['last_name'] = profile.last_name
        response['npm'] = view_user.npm
        response['batch'] = profile.batch
        response['email'] = profile.email
        response['linkedin_url'] = profile.linkedin_url
    else:
        response['first_name'] = "Unknown"
        response['last_name'] = "Unknown"
        response['npm'] = view_user.npm
        response['batch'] = "Unknown"
        response['email'] = "Unknown"
        response['linkedin_url'] = "Unknown"

    response['expertises'] = get_expertises_from_user(view_user)

    prepare_response_for_base(request, view_user, response)
    return render(request, 'main/profile.html', response)


def status(request, npm):
    view_user = get_user_from_npm(npm)
    if view_user is None:
        return HttpResponseNotFound()

    response = dict()
    response['status_list'] = Status.objects.filter(user=view_user).order_by('-created_at')
    prepare_response_for_base(request, view_user, response)
    return render(request, 'main/status.html', response)

def history(request, npm):
    view_user = get_user_from_npm(npm)
    if view_user is None:
        return HttpResponseNotFound()

    response = dict()
    response['histories'] = requests.get('https://private-e52a5-ppw2017.apiary-mock.com/riwayat').json()
    prepare_response_for_base(request, view_user, response)

    return render(request, 'main/history.html', response)


def prepare_response_for_base(request, user_to_view, response):
    own_profile = is_logged_in(request) and (get_npm(request) == user_to_view.npm)
    profile = get_profile_from_user(user_to_view)
    npm = user_to_view.npm
    name = "Unknown"
    profile_picture_url = static('img/PP.jpg')
    if profile is not None:
        name = profile.first_name + " " + profile.last_name
        profile_picture_url = profile.profile_picture_url
    status_count = Status.objects.filter(user=user_to_view).count()
    latest_status = ""
    if status_count > 0:
        latest_status = Status.objects.filter(user=user_to_view).order_by('-created_at')[0].content

    add_dict = {
        'logged_in': is_logged_in(request),
        'own_profile': own_profile,
        'npm': npm,
        'name': name,
        'status_count': status_count,
        'latest_status': latest_status,
        'profile_picture_url': profile_picture_url,
        'needs_to_edit': (own_profile and (profile is None))
    }

    response.update(add_dict)

tugas_main/templates/main/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <title>
        {% block title %} Tugas 2 PPW {% endblock %}
    </title>

    {% block head_script %}

    {% endblock %}
</head>
<body>

<content>
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2> {{ name }} </h2>
            </div>
            <div class="panel-body">
                <div class="row">
                    <img src="{{ profile_picture_url }}" class="col-xs-2" style="max-width:250px">
                    <div class="col-xs-10">
                        <h3>{{ status_count }} status posted</h3>
                        <h3 style="font-style: italic">{{ latest_status }}</h3>
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                {% if own_profile %}
                    <a href="{% url 'main:edit_profile' %}" class="btn btn-primary">Edit Profile
                        {% if needs_edit %}
                            (Please edit your profile first)
                        {% endif %}
                    </a>
                {% endif %}


                {% if logged_in %}
                    <a href="{% url 'auth:logout' %}" class="btn btn-danger">Logout</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container">
        <ul class="nav nav-tabs">
            <li id="profile"><a href="{% if own_profile %} {% url 'main:my_profile' %} {% else %} {% url 'main:profile' npm %} {% endif %}">Profile</a></li>
            <li id="status"><a href="{% if own_profile %} {% url 'main:my_status' %} {% else %} {% url 'main:status' npm %} {% endif %}">Status</a></li>
            <li id="history"><a href="{% if own_profile %} {% url 'main:my_history' %} {% else %} {% url 'main:history' npm %} {% endif %}">History</a></li>
            {% if own_profile %} <li id="friends"><a href="{% url 'main:my_friends' %}">Friends</a></li> {% endif %}
        </ul>
        <br/>
    </div>
    <div class="container">
        {% block content %}
            <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>

<!-- Jquery n Bootstrap Script -->
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block script %}
{% endblock %}
</body>
</html>